server:
  port: 8091

# Configuração do banco de dados PostgreSQL
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5434}/${DB_NAME:payment-db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Configuração do Kafka
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    admin:
      auto-create: true
    topic:
      orchestrator: ${KAFKA_TOPIC_ORCHESTRATOR:orchestrator}
      payment-success: ${KAFKA_TOPIC_PAYMENT-SUCCESS:payment-success}
      payment-fail: ${KAFKA_TOPIC_PAYMENT-FAIL:payment-fail}
    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP_ID:payment-group}
      auto-offset-reset: latest
    

# Configuração de logs
logging:
  level:
    org:
      apache:
        kafka: OFF