server:
  port: ${PORTA_ORDER_SERVICE}

# Kafka Configuration
spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    admin:
      auto-create: true
    topic:
      start-saga: ${KAFKA_TOPIC_START_SAGA}
      notify-ending: ${KAFKA_TOPIC_NOTIFY_ENDING}
    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP_ID}
      auto-offset-reset: latest

  # MongoDB Configuration
  data:
    mongodb:
      database: ${MONGODB_DATABASE}
      uri: mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@${MONGODB_HOST}:${MONGODB_PORT}/${MONGODB_DATABASE}?authSource=${MONGODB_AUTH_SOURCE}


# Logging Configuration
logging:
  level:
    org:
      apache:
        kafka: OFF
