server:
  port: 3000

# Kafka Configuration
spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    admin:
      auto-create: true
    topic:
      start-saga: ${KAFKA_TOPIC_START_SAGA:start-saga}
      notify-ending: ${KAFKA_TOPIC_NOTIFY_ENDING:notify-ending}
    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP_ID:order-group}
      auto-offset-reset: latest

  # MongoDB Configuration
  data:
    mongodb:
      database: ${MONGODB_DATABASE:order-db}
      uri: ${MONGODB_URI:mongodb://admin:123456@127.0.0.1:27018/order-db?authSource=admin}

# Logging Configuration
logging:
  level:
    org:
      apache:
        kafka: OFF
