server:
  port: 8090

# Configuração do banco de dados PostgreSQL
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:product-db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  sql:
    init:
      mode: always
      data-locations: classpath:import.sql
      continue-on-error: false

  # Configuração do Kafka
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    admin:
      auto-create: true
    topic:
      orchestrator: ${KAFKA_TOPIC_ORCHESTRATOR:orchestrator}
      product-validation-success: ${KAFKA_TOPIC_PRODUCT_VALIDATION_SUCCESS:product-validation-success}
      product-validation-fail: ${KAFKA_TOPIC_PRODUCT_VALIDATION_FAIL:product-validation-fail}
    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP_ID:product-validation-group}
      auto-offset-reset: latest

# Configuração de logs
logging:
  level:
    org:
      apache:
        kafka: OFF